# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure resolvers
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        image120x120:
            quality: 75
            filters:
                thumbnail: { size: [ 120, 120 ], mode: outbound }
        image240x240:
            quality: 75
            filters:
                thumbnail: { size: [ 240, 240 ], mode: outbound }