vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix: /images/uploads/users
            upload_destination: '%kernel.project_dir%/public/images/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
